server:
  port: 8080
#  context-path: /jude
spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/db_letter?characterEncoding=utf-8&useSSL=false
      url: jdbc:mysql://9df7c6b2a30f1182.natapp.cc:14725/db_letter?characterEncoding=utf-8&useSSL=false&
      #&useSSL=false&
      username: root
      #password: Asd147a..258..
      password: 123456
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
   thymeleaf:
    cache: false
    resources:
      static-locations: classpath:/static/
sms:
  api:
    baseUrl: https://openapi.danmi.com
    accountSid: 4de5da7c57a67200849572eb3a12ab2a
    authToken: 6fd2cae798640047d8d5cc501153fd7b