server:
  port: 8080
#  context-path: /jude
spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_letter?characterEncoding=utf-8&useSSL=false
      #&useSSL=false&
      username: root
      #password: Asd147a..258..
      password: 123456
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
   thymeleaf:
    cache: false
